import { join } from 'path';
import fse from 'fs-extra';

import esbootConfig from '@@/config';

export function writeMultiPlatform() {
  const { rootPath, platform, pageType, isSP } = esbootConfig.compileTimeConfig;

  if (isSP) return;

  fse.outputFileSync(
    join(rootPath, './helpers/multi-platforms.ts'),
    `// 📢 Do not manually modify, automatically generated by ESBoot.\nexport * from '@${platform}-${pageType}/helpers/multi-platforms';\n`
  );
}
