// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import routeProps from './routeProps';

if (process.env.NODE_ENV === 'development') {
  Object.entries(routeProps).forEach(([key, value]) => {
    const internalProps = ['path', 'id', 'parentId', 'isLayout', 'isWrapper', 'layout', 'clientLoader'];
    Object.keys(value).forEach((prop) => {
      if (internalProps.includes(prop)) {
        throw new Error(
          `[UmiJS] route '${key}' should not have '${prop}' prop, please remove this property in 'routeProps'.`
        )
      }
    })
  })
}

import React from 'react';

export async function getRoutes() {
  const routes = {"@@/global-layout":{"id":"@@/global-layout","path":"/","parentId":"docs-layout","isLayout":true},"docs-layout":{"id":"docs-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/Users/rocsun/Code/dz-library/esboot/_esboot-react/packages/docs/src/layouts/index.tsx')),
'docs-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-docs__Layout" */'/Users/rocsun/Code/dz-library/esboot/_esboot-react/packages/docs/src/.umi/plugin-docs/Layout.tsx')),
},
  };
}
