// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { FeatureItem, Features, Hero, Message, Tabbed } from '/Users/rocsun/Code/dz-library/esboot/_esboot-react/node_modules/.pnpm/@umijs+plugin-docs@4.0.71_react@18.2.0/node_modules/@umijs/plugin-docs/client/theme-doc/index.ts';
