// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import { useOutlet, useAppData, useLocation, Link, history } from 'umi';
import { $Layout as Layout } from '/Users/rocsun/Code/dz-library/esboot/_esboot-react/node_modules/.pnpm/@umijs+plugin-docs@4.0.71_react@18.2.0/node_modules/@umijs/plugin-docs/client/theme-doc/index.ts';
const themeConfig = {}

themeConfig.locales = {};

export default () => {
  const outlet = useOutlet();
  const appData = useAppData();
  const location = useLocation();
  return (
    <Layout appData={appData} components={{Link}} themeConfig={themeConfig} location={location} history={history}>
      <div>{ outlet }</div>
    </Layout>
  );
};
